name: Build & Dependency Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

        # Here for my benefit so I remember what these flags do and don't have to look them up everytime
        # -B turns on batch mode
        #   Disables interactive input and reduces progress output. This is mainly for CI so the build never waits for user input
        # -ntp turns off transfer progress
        #   Turns off the animated dependency download progress lines. Logs become stable and much shorter
      - name: Build & test with Maven
        run: mvn -B -ntp clean verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            **/target/site/jacoco/**
            **/target/jacoco.exec
            **/target/site/jacoco-aggregate/**

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco-aggregate/jacoco.xml,
          token: ${{ secrets.JACOCO_GITHUB_SECRET }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Check dependency & plugin updates
        run: |
          mvn -B -ntp \
            versions:display-dependency-updates \
            versions:display-plugin-updates \
            -DprocessAllModules=true
        continue-on-error: true

      - name: Upload shaded app jar
        uses: actions/upload-artifact@v4
        with:
          name: zoned-dns-app
          path: app/target/zoned-dns-app-*.jar
          if-no-files-found: ignore
