<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.hedges</groupId>
    <artifactId>zoned-dns</artifactId>
    <version>0.1.0</version>
  </parent>

  <artifactId>zoned-dns-coverage</artifactId>
  <packaging>pom</packaging>

  <dependencies>
    <dependency>
      <groupId>io.hedges</groupId>
      <artifactId>zoned-dns-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.hedges</groupId>
      <artifactId>zoned-dns-netty</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.hedges</groupId>
      <artifactId>zoned-dns-app</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
            <configuration>
              <outputDirectory>${session.topLevelProject.build.directory}/site/jacoco-aggregate</outputDirectory>
              <dataFileIncludes>
                <dataFileInclude>target/jacoco.exec</dataFileInclude>
              </dataFileIncludes>
              <dataFileExcludes>
                <dataFileExclude>target/jacoco-it.exec</dataFileExclude>
              </dataFileExcludes>
              <formats>
                <format>XML</format>
                <format>HTML</format>
              </formats>
            </configuration>
          </execution>
          <execution>
            <id>report-aggregate-it</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
            <configuration>
              <outputDirectory>${session.topLevelProject.build.directory}/site/jacoco-aggregate-it</outputDirectory>
              <dataFileIncludes>
                <dataFileInclude>target/jacoco-it.exec</dataFileInclude>
              </dataFileIncludes>
              <dataFileExcludes>
                <dataFileExclude>target/jacoco.exec</dataFileExclude>
              </dataFileExcludes>
              <formats>
                <format>XML</format>
                <format>HTML</format>
              </formats>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
